package dockername

import "testing"

func TestIsDockerAssigned(t *testing.T) {
	cases := []struct {
		name string
		want bool
	}{
		{"adoring_saha", true},      // real Docker auto-name
		{"focused_turing", true},    // real Docker auto-name
		{"focused_turing3", true},   // collision suffix (single trailing digit)
		{"boring_wozniak", true},    // never generated by Docker, but is vocabulary
		{"backrest", false},         // explicit name, no underscore
		{"postgres", false},         // explicit name
		{"myproj_web_1", false},     // compose-style: halves not in the word lists
		{"web_app", false},          // both halves outside the lists
		{"adoring", false},          // adjective only, no surname
		{"adoring_notarealsurname", false},
		{"_saha", false},
		{"adoring_", false},
		{"", false},
	}
	for _, c := range cases {
		if got := IsDockerAssigned(c.name); got != c.want {
			t.Errorf("IsDockerAssigned(%q) = %v, want %v", c.name, got, c.want)
		}
	}
}
